spring:
  datasource:
    url: jdbc:mysql://localhost:3306/delivery?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create / update / validate / none 중 선택
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect  # MySQL 8 기준

server:
  port: 8080
